version: '3.3'

services:
    app:
        build:
            context: .
            dockerfile: ./compose/Dockerfile
        command: npm run start
        volumes:
            - ./:/app/
            - nodejs-logs:/root/.npm/_logs/
        network_mode: host 
        env_file:
            - .env
        depends_on:
            - mongo
    mongo:
        image: mongo:4.4
        ports:
            - 27017:27017
        env_file:
            - .env
        volumes:
            - mongodb-data:/data/db

volumes:
    mongodb-data:
    nodejs-logs: